name: Birthday-Greeting-Demo
kind: pipeline
type: exec

steps:
  - name: Maven Package
    commands:
      - mvn package --quiet
    when:
      event:
        - push
  - name: Build Docker Image
    commands:
      - docker build . -t birthday-greeting-demo-image
    when:
      event:
        - push
  - name: Deploy
    commands:
      - docker rm -f birthday-greeting-demo
      - docker run -d --name birthday-greeting-demo -p 27000:8080 birthday-greeting-demo-image
    when:
      event:
        - push

