spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://140.112.31.199:27001/my_database
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver